language: node_js
node_js:
  - "node"

before_install:
  - npx firebase use $FIREBASE_PROJECT_ID

script:
  - npm run lint

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

cache: npm

notifications:
  email:
    on_failure: change
    on_success: change
