language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_script:
  - npm i --silent

script:
  - npm run lint

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

cache: npm

notifications:
  email:
    # Only send notifications when travis status changes
    on_failure: change
    on_success: change
